package stack

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Route is one virtual host the proxy serves.
type Route struct {
	Domain string
	// Address is the container's address and port as it was when the route was
	// built. It is what the request is sent to.
	Address string
	// Backend is the container's name and port. The runtime resolves it, which
	// is how a container recreated without containerctl is found again.
	Backend string
	Scheme  string // http or https
	ipv4    string // current instance identity for the reload generation
	started string
}

// HealthPath is served over plain HTTP by the default server and returns the
// generation of the configuration nginx is running. Reloading is asynchronous:
// the workers being replaced hold the listening sockets until they finish
// shutting down, and one of them can accept a connection it does not serve.
// Callers poll this path to confirm the new configuration is in use.
const HealthPath = "/__containerctl/health"

// RouteHeader names which of a route's two targets answered: "address" for the
// address the configuration was built from, "name" for the fallback the runtime
// resolves. It is what tells a slow answer from the wrong path apart from a
// slow service.
const RouteHeader = "X-Containerctl-Route"

// A container is given a new address every time it is recreated, and the proxy
// names its backends rather than addressing them. Three settings decide what
// happens between the moment the address changes and the moment the proxy
// follows it.
const (
	// heldAddress is how long nginx keeps a name it resolved. The name is the
	// fallback, and the runtime answers with a container's previous address for
	// about fifteen seconds after it is recreated, so holding it any longer
	// only adds to that.
	heldAddress = "1s"
	// connectWait is how long a connection attempt may take. nginx waits a
	// minute by default, which turns an address the container no longer holds
	// into a hang; two seconds turns it into a failure the fallback answers.
	connectWait = "2s"
)

// RenderNginx writes the server blocks for routes into confDir/stack.conf.
//
// defaultCert names the certificate the default server presents for a name
// under a delegated domain that has no route. resolver is the container
// network's DNS address; backends are named rather than addressed, so a
// restarted container is reached at its new address. generation identifies this
// configuration and is returned by HealthPath.
func RenderNginx(confDir string, routes []Route, resolver, defaultCert, generation string) error {
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	if len(routes) == 0 {
		return fmt.Errorf("no routes to render")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by containerctl - do not edit\n\n")
	b.WriteString("server_names_hash_bucket_size 512;\n\n")
	fmt.Fprintf(&b, "resolver %s valid=%s ipv6=off;\n\n", resolver, heldAddress)
	b.WriteString("map $http_upgrade $connection_upgrade {\n    default upgrade;\n    ''      close;\n}\n\n")

	// Plain HTTP redirects to HTTPS. The health endpoint answers on HTTP so no
	// certificate is required.
	fmt.Fprintf(&b, "server {\n    listen 80 default_server;\n")
	fmt.Fprintf(&b, "    location = %s {\n", HealthPath)
	fmt.Fprintf(&b, "        access_log off;\n        default_type text/plain;\n")
	fmt.Fprintf(&b, "        return 200 %q;\n    }\n", generation+"\n")
	fmt.Fprintf(&b, "    location / {\n        return 308 https://$host$request_uri;\n    }\n}\n\n")
	fmt.Fprintf(&b, "server {\n    listen 443 ssl default_server;\n    http2 on;\n"+
		"    ssl_certificate     /etc/nginx/certs/%s.crt;\n"+
		"    ssl_certificate_key /etc/nginx/certs/%s.key;\n"+
		"    return 404;\n}\n\n", defaultCert, defaultCert)

	for _, r := range routes {
		fmt.Fprintf(&b, "server {\n")
		fmt.Fprintf(&b, "    listen 443 ssl;\n    http2 on;\n")
		fmt.Fprintf(&b, "    server_name %s;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", r.Domain)
		fmt.Fprintf(&b, "    client_max_body_size 0;\n")
		// The request goes to the address the route was built from, so it does
		// not depend on the runtime's DNS, which answers with a container's
		// previous address for about fifteen seconds after it is recreated.
		// A container recreated without containerctl keeps its name, so a
		// route whose address stops answering falls back to the name.
		fmt.Fprintf(&b, "    location / {\n")
		if r.Address != "" {
			fmt.Fprintf(&b, "        set $backend \"%s://%s\";\n", r.Scheme, r.Address)
			fmt.Fprintf(&b, "        set $byname \"%s://%s\";\n", r.Scheme, r.Backend)
			fmt.Fprintf(&b, "        error_page 502 504 = @byname;\n")
		} else {
			fmt.Fprintf(&b, "        set $backend \"%s://%s\";\n", r.Scheme, r.Backend)
		}
		b.WriteString(proxyPass("$backend", addressPath(r)))
		fmt.Fprintf(&b, "    }\n")
		if r.Address != "" {
			fmt.Fprintf(&b, "    location @byname {\n")
			b.WriteString(proxyPass("$byname", "name"))
			fmt.Fprintf(&b, "    }\n")
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	return os.WriteFile(filepath.Join(confDir, "stack.conf"), []byte(b.String()), 0o644)
}

// addressPath names the target the primary location sends to. A route with no
// address of its own sends to the name.
func addressPath(r Route) string {
	if r.Address == "" {
		return "name"
	}
	return "address"
}

// proxyPass returns the directives that forward a request to the target held in
// the given variable. The address and the name fallback use the same ones.
func proxyPass(target, path string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "        add_header %s %s always;\n", RouteHeader, path)
	fmt.Fprintf(&b, "        proxy_pass %s;\n", target)
	fmt.Fprintf(&b, "        proxy_connect_timeout %s;\n", connectWait)
	fmt.Fprintf(&b, "        proxy_ssl_verify off;\n")
	fmt.Fprintf(&b, "        proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "        proxy_set_header Host $host;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Real-IP $remote_addr;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-Proto https;\n")
	fmt.Fprintf(&b, "        proxy_set_header Upgrade $http_upgrade;\n")
	fmt.Fprintf(&b, "        proxy_set_header Connection $connection_upgrade;\n")
	return b.String()
}
