package stack

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Route is one virtual host the proxy serves.
type Route struct {
	Domain string
	// Address is the container's address and port as it was when the route was
	// built. It is what the request is sent to.
	Address string
	// Backend is the container's name and port. The runtime resolves it, which
	// is how a container recreated without containerctl is found again.
	Backend string
	Scheme  string // http or https
	ipv4    string // current instance identity for the reload generation
	started string
}

// HealthPath is served over plain HTTP by the default server and returns the
// generation of the configuration nginx is running. Reloading is asynchronous:
// the workers being replaced hold the listening sockets until they finish
// shutting down, and one of them can accept a connection it does not serve.
// Callers poll this path to confirm the new configuration is in use.
const HealthPath = "/__containerctl/health"

// RouteHeader names which of a route's two targets answered: "address" for the
// address the configuration was built from, "name" for the fallback the runtime
// resolves. It is what tells a slow answer from the wrong path apart from a
// slow service.
const RouteHeader = "X-Containerctl-Route"

// PeerPath is served over the peer link without a client certificate. It has to
// answer before there is an approval, so it cannot ask for one.
const PeerPath = "/__containerctl/peer"

// NginxConfig is everything the proxy configuration is written from.
type NginxConfig struct {
	Routes []Route
	// Resolver is the container network's DNS address, used by the fallback
	// that reaches a backend by name.
	Resolver string
	// DefaultCert names the certificate the default server presents for a name
	// under a delegated domain that has no route.
	DefaultCert string
	// Generation identifies this configuration and is returned by HealthPath.
	Generation string

	// PeerPort is where this machine's link answers. Zero leaves the link out,
	// which is a machine with no peers.
	PeerPort int
	// PeerAuthorities is the file holding the authorities whose client
	// certificates the link accepts.
	PeerAuthorities string
	// ClientCert and ClientKey are what this machine presents on a peer's link.
	ClientCert string
	ClientKey  string
	// PeerRoutes are the domains an approved peer serves. This machine answers
	// them and forwards them over that peer's link.
	PeerRoutes []PeerRoute
}

// PeerRoute is one domain a peer serves.
type PeerRoute struct {
	Domain string
	// Address is the peer's link, as host:port.
	Address string
	// Authority is the file holding that peer's certificate authority, which
	// the peer's own certificate is checked against.
	Authority string
}

// A container is given a new address every time it is recreated, and the proxy
// names its backends rather than addressing them. Three settings decide what
// happens between the moment the address changes and the moment the proxy
// follows it.
const (
	// heldAddress is how long nginx keeps a name it resolved. The name is the
	// fallback, and the runtime answers with a container's previous address for
	// about fifteen seconds after it is recreated, so holding it any longer
	// only adds to that.
	heldAddress = "1s"
	// connectWait is how long a connection attempt may take. nginx waits a
	// minute by default, which turns an address the container no longer holds
	// into a hang; two seconds turns it into a failure the fallback answers.
	connectWait = "2s"
)

// RenderNginx writes the server blocks for routes into confDir/stack.conf.
//
// defaultCert names the certificate the default server presents for a name
// under a delegated domain that has no route. resolver is the container
// network's DNS address; backends are named rather than addressed, so a
// restarted container is reached at its new address. generation identifies this
// configuration and is returned by HealthPath.
func RenderNginx(confDir string, routes []Route, resolver, defaultCert, generation string) error {
	return RenderNginxConfig(confDir, NginxConfig{
		Routes: routes, Resolver: resolver, DefaultCert: defaultCert, Generation: generation,
	})
}

// RenderNginxConfig writes the whole configuration, including the peer link and
// the domains approved peers serve.
func RenderNginxConfig(confDir string, c NginxConfig) error {
	routes, resolver, defaultCert, generation := c.Routes, c.Resolver, c.DefaultCert, c.Generation
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	if len(routes) == 0 && len(c.PeerRoutes) == 0 {
		return fmt.Errorf("no routes to render")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by containerctl - do not edit\n\n")
	b.WriteString("server_names_hash_bucket_size 512;\n\n")
	fmt.Fprintf(&b, "resolver %s valid=%s ipv6=off;\n\n", resolver, heldAddress)
	b.WriteString("map $http_upgrade $connection_upgrade {\n    default upgrade;\n    ''      close;\n}\n\n")

	// Plain HTTP redirects to HTTPS. The health endpoint answers on HTTP so no
	// certificate is required.
	fmt.Fprintf(&b, "server {\n    listen 80 default_server;\n")
	fmt.Fprintf(&b, "    location = %s {\n", HealthPath)
	fmt.Fprintf(&b, "        access_log off;\n        default_type text/plain;\n")
	fmt.Fprintf(&b, "        return 200 %q;\n    }\n", generation+"\n")
	fmt.Fprintf(&b, "    location / {\n        return 308 https://$host$request_uri;\n    }\n}\n\n")
	fmt.Fprintf(&b, "server {\n    listen 443 ssl default_server;\n    http2 on;\n"+
		"    ssl_certificate     /etc/nginx/certs/%s.crt;\n"+
		"    ssl_certificate_key /etc/nginx/certs/%s.key;\n"+
		"    return 404;\n}\n\n", defaultCert, defaultCert)

	for _, r := range routes {
		fmt.Fprintf(&b, "server {\n")
		fmt.Fprintf(&b, "    listen 443 ssl;\n    http2 on;\n")
		fmt.Fprintf(&b, "    server_name %s;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", r.Domain)
		fmt.Fprintf(&b, "    client_max_body_size 0;\n")
		// The request goes to the address the route was built from, so it does
		// not depend on the runtime's DNS, which answers with a container's
		// previous address for about fifteen seconds after it is recreated.
		// A container recreated without containerctl keeps its name, so a
		// route whose address stops answering falls back to the name.
		fmt.Fprintf(&b, "    location / {\n")
		if r.Address != "" {
			fmt.Fprintf(&b, "        set $backend \"%s://%s\";\n", r.Scheme, r.Address)
			fmt.Fprintf(&b, "        set $byname \"%s://%s\";\n", r.Scheme, r.Backend)
			fmt.Fprintf(&b, "        error_page 502 504 = @byname;\n")
		} else {
			fmt.Fprintf(&b, "        set $backend \"%s://%s\";\n", r.Scheme, r.Backend)
		}
		b.WriteString(proxyPass("$backend", addressPath(r)))
		fmt.Fprintf(&b, "    }\n")
		if r.Address != "" {
			fmt.Fprintf(&b, "    location @byname {\n")
			b.WriteString(proxyPass("$byname", "name"))
			fmt.Fprintf(&b, "    }\n")
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	writePeerLink(&b, c)
	writePeerRoutes(&b, c)
	return os.WriteFile(filepath.Join(confDir, "stack.conf"), []byte(b.String()), 0o644)
}

// writePeerLink adds the port approved peers reach this machine on. What this
// machine serves is offered there as well, to a client holding a certificate
// from an authority this machine has approved. The endpoint a machine is
// approved from answers without one.
func writePeerLink(b *strings.Builder, c NginxConfig) {
	if c.PeerPort == 0 {
		return
	}
	fmt.Fprintf(b, "server {\n    listen %d ssl default_server;\n    http2 on;\n", c.PeerPort)
	fmt.Fprintf(b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", c.DefaultCert)
	fmt.Fprintf(b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", c.DefaultCert)
	// Nothing is asked for and nothing is checked here: this server answers the
	// endpoint, and the endpoint is what an approval is made from.
	b.WriteString("    ssl_verify_client optional_no_ca;\n")
	fmt.Fprintf(b, "    location = %s {\n", PeerPath)
	b.WriteString("        default_type application/json;\n")
	b.WriteString("        alias /etc/nginx/conf.d/peer.json;\n    }\n")
	b.WriteString("    location / {\n        return 404;\n    }\n}\n\n")

	// Without an approved authority there is nothing to check a client against,
	// so this machine's own domains are not offered on the link yet. The
	// document above still answers, which is how the first peer is approved.
	if c.PeerAuthorities == "" {
		return
	}
	for _, r := range c.Routes {
		fmt.Fprintf(b, "server {\n    listen %d ssl;\n    http2 on;\n", c.PeerPort)
		fmt.Fprintf(b, "    server_name %s;\n", r.Domain)
		fmt.Fprintf(b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", r.Domain)
		fmt.Fprintf(b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", r.Domain)
		fmt.Fprintf(b, "    ssl_client_certificate %s;\n", c.PeerAuthorities)
		b.WriteString("    ssl_verify_client on;\n")
		b.WriteString("    client_max_body_size 0;\n")
		b.WriteString("    location / {\n")
		fmt.Fprintf(b, "        set $backend \"%s://%s\";\n", r.Scheme, addressOrName(r))
		b.WriteString(proxyPass("$backend", addressPath(r)))
		b.WriteString("    }\n}\n\n")
	}
}

// writePeerRoutes adds the domains approved peers serve. This machine answers
// them with a certificate it issued and forwards them over the peer's link with
// its own client certificate, so nothing of the peer is installed here.
func writePeerRoutes(b *strings.Builder, c NginxConfig) {
	for _, r := range c.PeerRoutes {
		b.WriteString("server {\n    listen 443 ssl;\n    http2 on;\n")
		fmt.Fprintf(b, "    server_name %s;\n", r.Domain)
		fmt.Fprintf(b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", r.Domain)
		fmt.Fprintf(b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", r.Domain)
		b.WriteString("    client_max_body_size 0;\n")
		b.WriteString("    location / {\n")
		fmt.Fprintf(b, "        add_header %s peer always;\n", RouteHeader)
		fmt.Fprintf(b, "        proxy_pass https://%s;\n", r.Address)
		fmt.Fprintf(b, "        proxy_connect_timeout %s;\n", connectWait)
		fmt.Fprintf(b, "        proxy_ssl_certificate           %s;\n", c.ClientCert)
		fmt.Fprintf(b, "        proxy_ssl_certificate_key       %s;\n", c.ClientKey)
		fmt.Fprintf(b, "        proxy_ssl_trusted_certificate   %s;\n", r.Authority)
		b.WriteString("        proxy_ssl_verify        on;\n")
		b.WriteString("        proxy_ssl_server_name   on;\n")
		fmt.Fprintf(b, "        proxy_ssl_name          %s;\n", r.Domain)
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Host $host;\n")
		b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
		b.WriteString("    }\n}\n\n")
	}
}

// addressOrName returns what a route is sent to: its address when it has one,
// and the container's name otherwise.
func addressOrName(r Route) string {
	if r.Address != "" {
		return r.Address
	}
	return r.Backend
}

// addressPath names the target the primary location sends to. A route with no
// address of its own sends to the name.
func addressPath(r Route) string {
	if r.Address == "" {
		return "name"
	}
	return "address"
}

// proxyPass returns the directives that forward a request to the target held in
// the given variable. The address and the name fallback use the same ones.
func proxyPass(target, path string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "        add_header %s %s always;\n", RouteHeader, path)
	fmt.Fprintf(&b, "        proxy_pass %s;\n", target)
	fmt.Fprintf(&b, "        proxy_connect_timeout %s;\n", connectWait)
	fmt.Fprintf(&b, "        proxy_ssl_verify off;\n")
	fmt.Fprintf(&b, "        proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "        proxy_set_header Host $host;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Real-IP $remote_addr;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-Proto https;\n")
	fmt.Fprintf(&b, "        proxy_set_header Upgrade $http_upgrade;\n")
	fmt.Fprintf(&b, "        proxy_set_header Connection $connection_upgrade;\n")
	return b.String()
}
