package stack

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Route is one virtual host the proxy serves.
type Route struct {
	Domain  string
	Backend string // host:port reachable from inside the container network
	Scheme  string // http or https
}

// HealthPath is served over plain HTTP by the default server and returns the
// generation of the configuration nginx is running. Reloading is asynchronous:
// the workers being replaced hold the listening sockets until they finish
// shutting down, and one of them can accept a connection it does not serve.
// Callers poll this path to confirm the new configuration is in use.
const HealthPath = "/__containerctl/health"

// RenderNginx writes the server blocks for routes into confDir/stack.conf.
//
// defaultCert names the certificate the default server presents for a name
// under a delegated domain that has no route. resolver is the container
// network's DNS address; backends are named rather than addressed, so a
// restarted container is reached at its new address. generation identifies this
// configuration and is returned by HealthPath.
func RenderNginx(confDir string, routes []Route, resolver, defaultCert, generation string) error {
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	if len(routes) == 0 {
		return fmt.Errorf("no routes to render")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by containerctl - do not edit\n\n")
	fmt.Fprintf(&b, "resolver %s valid=10s ipv6=off;\n\n", resolver)
	b.WriteString("map $http_upgrade $connection_upgrade {\n    default upgrade;\n    ''      close;\n}\n\n")

	// Plain HTTP redirects to HTTPS. The health endpoint answers on HTTP so no
	// certificate is required.
	fmt.Fprintf(&b, "server {\n    listen 80 default_server;\n")
	fmt.Fprintf(&b, "    location = %s {\n", HealthPath)
	fmt.Fprintf(&b, "        access_log off;\n        default_type text/plain;\n")
	fmt.Fprintf(&b, "        return 200 %q;\n    }\n", generation+"\n")
	fmt.Fprintf(&b, "    location / {\n        return 308 https://$host$request_uri;\n    }\n}\n\n")
	fmt.Fprintf(&b, "server {\n    listen 443 ssl default_server;\n    http2 on;\n"+
		"    ssl_certificate     /etc/nginx/certs/%s.crt;\n"+
		"    ssl_certificate_key /etc/nginx/certs/%s.key;\n"+
		"    return 404;\n}\n\n", defaultCert, defaultCert)

	for _, r := range routes {
		fmt.Fprintf(&b, "server {\n")
		fmt.Fprintf(&b, "    listen 443 ssl;\n    http2 on;\n")
		fmt.Fprintf(&b, "    server_name %s;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate     /etc/nginx/certs/%s.crt;\n", r.Domain)
		fmt.Fprintf(&b, "    ssl_certificate_key /etc/nginx/certs/%s.key;\n", r.Domain)
		fmt.Fprintf(&b, "    client_max_body_size 0;\n")
		fmt.Fprintf(&b, "    location / {\n")
		fmt.Fprintf(&b, "        set $backend \"%s://%s\";\n", r.Scheme, r.Backend)
		fmt.Fprintf(&b, "        proxy_pass $backend;\n")
		fmt.Fprintf(&b, "        proxy_ssl_verify off;\n")
		fmt.Fprintf(&b, "        proxy_http_version 1.1;\n")
		fmt.Fprintf(&b, "        proxy_set_header Host $host;\n")
		fmt.Fprintf(&b, "        proxy_set_header X-Real-IP $remote_addr;\n")
		fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		fmt.Fprintf(&b, "        proxy_set_header X-Forwarded-Proto https;\n")
		fmt.Fprintf(&b, "        proxy_set_header Upgrade $http_upgrade;\n")
		fmt.Fprintf(&b, "        proxy_set_header Connection $connection_upgrade;\n")
		fmt.Fprintf(&b, "    }\n}\n\n")
	}
	return os.WriteFile(filepath.Join(confDir, "stack.conf"), []byte(b.String()), 0o644)
}
